-- MySQL Script generated by MySQL Workbench
-- Tue Mar 18 16:07:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema retencionAprendices
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `aprendiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aprendiz` (
  `idAprendiz` INT NOT NULL AUTO_INCREMENT,
  `nombreCompleto` VARCHAR(50) NOT NULL,
  `programaAcademico` VARCHAR(50) NOT NULL,
  `trimestre` INT NOT NULL,
  `centroAcademico` VARCHAR(50) NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `telefono` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idAprendiz`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestor` (
  `idGestor` INT NULL AUTO_INCREMENT,
  `nombreCompleto` VARCHAR(50) NOT NULL,
  `centroAcademico` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `competencias` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGestor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reporte` (
  `idReporte` INT NULL AUTO_INCREMENT,
  `fechaCreacion` DATETIME NOT NULL,
  `tipoReporte` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `conclusiones` VARCHAR(100) NOT NULL,
  `fkIdAprendiz` INT NOT NULL,
  `fkIdGestor` INT NOT NULL,
  PRIMARY KEY (`idReporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `objetivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `objetivos` (
  `idObjetivos` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) NOT NULL,
  `fechaEstablecimiento` DATE NOT NULL,
  `fechaCumplimiento` DATE NOT NULL,
  `estado` TINYINT NOT NULL,
  `fkIdReporte` INT NOT NULL,
  PRIMARY KEY (`idObjetivos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `profesionalBienestar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `profesionalBienestar` (
  `idProfesionalBienestar` INT NOT NULL AUTO_INCREMENT,
  `nombreCompleto` VARCHAR(50) NOT NULL,
  `centroAcademico` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `numTarjetaProfesional` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfesionalBienestar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reporte_profesionalBienestar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reporte_profesionalBienestar` (
  `fkIdReporte` INT NOT NULL,
  `fkIdProfesionalBiesnestar` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intervención`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intervención` (
  `idIntervención` INT NOT NULL AUTO_INCREMENT,
  `tipoIntervencion` VARCHAR(60) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `conclusiones` VARCHAR(45) NOT NULL,
  `responsable` VARCHAR(45) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `resultados` VARCHAR(45) NOT NULL,
  `fkIntervencion` INT NOT NULL,
  `fkObjetivos` INT NOT NULL,
  PRIMARY KEY (`idIntervención`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alerta` (
  `idalerta` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL,
  PRIMARY KEY (`idalerta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intervencion_alerta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intervencion_alerta` (
  `fkIdIntervencion` INT NOT NULL,
  `fkIdAlerta` INT NOT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tipoIntervencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tipoIntervencion` (
  `idTipoIntervencion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `concluciones` VARCHAR(45) NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFin` DATE NOT NULL,
  `responsable` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoIntervencion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intervencion_tipoIntervencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intervencion_tipoIntervencion` (
  `fkIdIntervencion` INT NOT NULL,
  `fkIdTipoIntervencion` INT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
