-- MySQL Script generated by MySQL Workbench
-- Thu Mar 27 11:39:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema retencionAprendices
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rol` (
  `idRol` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `usuario` (
  `idUsuario` INT NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `tipoCoordinador` VARCHAR(50) NOT NULL,
  `gestor` TINYINT NULL,
  `fkIdRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  CONSTRAINT `fkIdRol`
    FOREIGN KEY (`fkIdRol`)
    REFERENCES `rol` (`idRol`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `programaFormacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `programaFormacion` (
  `idProgramaFormacion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProgramaFormacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `grupo` (
  `idGrupo` INT NOT NULL,
  `ficha` VARCHAR(45) NOT NULL,
  `jornada` VARCHAR(45) NOT NULL,
  `modalidad` VARCHAR(45) NOT NULL,
  `fkIdProgramaFormacion` INT NOT NULL,
  PRIMARY KEY (`idGrupo`),
  CONSTRAINT `fkIdProgramaFormacion`
    FOREIGN KEY (`fkIdProgramaFormacion`)
    REFERENCES `programaFormacion` (`idProgramaFormacion`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `aprendiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aprendiz` (
  `idAprendiz` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `trimestre` VARCHAR(20) NOT NULL,
  `programaFormacion` VARCHAR(40) NOT NULL,
  `ficha` VARCHAR(20) NOT NULL,
  `fkIdUsuario` INT NOT NULL,
  `fkIdGrupo` INT NOT NULL,
  PRIMARY KEY (`idAprendiz`),
  CONSTRAINT `fkIdUsuario`
    FOREIGN KEY (`fkIdUsuario`)
    REFERENCES `usuario` (`idUsuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdGrupo`
    FOREIGN KEY (`fkIdGrupo`)
    REFERENCES `grupo` (`idGrupo`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `reporte` (
  `idReporte` INT NULL AUTO_INCREMENT,
  `fechaCreacion` DATETIME NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `direccionamiento` VARCHAR(15) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `fkIdAprendiz` INT NOT NULL,
  `fkIdUsuario` INT NOT NULL,
  PRIMARY KEY (`idReporte`),
  CONSTRAINT `fkIdAprendiz`
    FOREIGN KEY (`fkIdAprendiz`)
    REFERENCES `aprendiz` (`idAprendiz`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdUsuario2`
    FOREIGN KEY (`fkIdUsuario`)
    REFERENCES `usuario` (`idUsuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `causa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `causa` (
  `idCausa` INT NOT NULL,
  `causa` VARCHAR(100) NOT NULL,
  `variables` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idCausa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `categoria` (
  `idCategoria` INT NOT NULL,
  `nombre` VARCHAR(80) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `direccionamiento` VARCHAR(15) NOT NULL,
  `fkIdCausa` INT NOT NULL,
  PRIMARY KEY (`idCategoria`),
  CONSTRAINT `fkIdCausa`
    FOREIGN KEY (`fkIdCausa`)
    REFERENCES `causa` (`idCausa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estrategias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estrategias` (
  `idEstrategias` INT NOT NULL,
  `estrategia` VARCHAR(80) NOT NULL,
  `fkIdCategoria` INT NOT NULL,
  PRIMARY KEY (`idEstrategias`),
  CONSTRAINT `fkIdCategoria`
    FOREIGN KEY (`fkIdCategoria`)
    REFERENCES `categoria` (`idCategoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `intervencion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `intervencion` (
  `idIntervención` INT NOT NULL AUTO_INCREMENT,
  `fechaCreacion` DATETIME NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fkIdEstrategias` INT NOT NULL,
  `fkIdReporte` INT NOT NULL,
  `fkIdUsuario` INT NOT NULL,
  PRIMARY KEY (`idIntervención`),
  CONSTRAINT `fkIdEstrategias`
    FOREIGN KEY (`fkIdEstrategias`)
    REFERENCES `estrategias` (`idEstrategias`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdReporte`
    FOREIGN KEY (`fkIdReporte`)
    REFERENCES `reporte` (`idReporte`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdUsuario3`
    FOREIGN KEY (`fkIdUsuario`)
    REFERENCES `usuario` (`idUsuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `causa_reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `causa_reporte` (
  `fkIdReporte` INT NOT NULL,
  `fkIdCausa` INT NOT NULL,
  CONSTRAINT `fkIdReporte2`
    FOREIGN KEY (`fkIdReporte`)
    REFERENCES `reporte` (`idReporte`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fkIdCausa2`
    FOREIGN KEY (`fkIdCausa`)
    REFERENCES `causa` (`idCausa`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `resultado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `resultado` (
  `idResultado` INT NOT NULL,
  `resultadocol` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idResultado`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
